#%RAML 1.0
title: Hawu-Akka-Playground
baseUri: http://127.0.0.1
version: v1
protocols: [ HTTPS ]
mediaType: application/json

types:

/v1:

  get:
    description: ???
    responses:
      200:
        description: ???
      500:
        description: ServiceUnavailable, an unexpected error occurred

    post:
      description: ???
      responses:
        200:
          description: ???
        500:
          description: ServiceUnavailable, an unexpected error occurred

    put:
      description: ???
      responses:
        200:
          description: ???
        500:
          description: ServiceUnavailable, an unexpected error occurred

    delete:
      description: ???
      responses:
        200:
          description: ???
        500:
          description: ServiceUnavailable, an unexpected error occurred

